Animal = str(input("Animal: "))
Verb = str(input("verb: "))
Random_Number = int(input("RandomNumber: "))
Random_number_2 = int(input("Random number 2: "))
Place = str(input("Location: "))
Color = str(input("Color: "))
Body_Part = str(input("Body Part: "))
print("One day I was walking my "+ str(Animal))
print("As we were walking we came across my "+ str(Place))
print("What is weird about it is that it is "+ str(Color))
print("While walking by we were attacked by "+ str(Random_Number)) 
print(Animal)
print("impusivly, I started "+ str(Verb))
print("But then they had "+ str(Random_number_2))
print("More show up and attack my "+ str(Body_Part))
print("So I ran away with my "+ str(Animal))
print("hello")